### ISSUE TITLE
assign design.matrix to element of model.object in functions_clean_UKvars.

### ISSUE THREAD

**Issue by myoung3** [myoung3/regionalkriging#17]
currently assigns directly to model.obj

**Comment by swlim2** [comment]
Assigned. Do you know where model.obj$design.matrix should be used again? I believe so far the only function using it is make_nat_design. Models seem to mostly use model.obj$X constructed in the PLSK.full function.

**Comment by myoung3** [comment]
it should be used in make_reg_design

**Comment by swlim2** [comment]
yup confirmed and fixed
